repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.2
    hooks:
      - id: isort
        args: [--profile=black]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
      - id: clang-format
        exclude: "^python/.*"

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: [ "--dangle-parens", "--in-place" ]
      - id: cmake-lint
        args: [ "--dangle-parens" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
