[build-system]
requires = ["setuptools >= 40.6.0", "Cython", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "pytest {project}/python"
test-requires = "pytest"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
