name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install build tools
        run: sudo apt-get install build-essential cmake
      - name: Test
        run: |
          mkdir build && cd build
          cmake .. && cmake --build . && ./gfc_test
