name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install build tools
        run: sudo apt-get install build-essential cmake
      - name: Test C library
        run: |
          mkdir build && cd build
          cmake -DWITH_SANITIZER=ON .. && cmake --build . && ./gfc_test
      - name: Test Python bindings
        run: |
          pip install -e .
          pip install pytest
          pytest

  pypi:
    needs: [test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Build wheels
        uses: joerick/cibuildwheel@2.7.0
        with:
          output-dir: dist
      - uses: dioptra-io/publish-python-action@v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          upload: ${{ startsWith(github.ref, 'refs/tags/v') }}
          wheel: false
